config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'profile', to: 'users#profile'
  post 'signup', to: 'users#signup_user'
  post 'login', to: 'users#login_user'
  patch 'profile/edit_profile', to: 'users#edit_profile'
  patch 'profile/update_profile_img', to: 'users#update_profile_img'
  get 'users/:id', to: 'users#show'
  post 'users/:id/following', to: 'users#follow_user'
  delete 'logout', to: 'users#logout_user'

  scope "articles" do
    get "/autocomplete" => "articles#autocomplete" 
    get "/search" => "articles#search"
    get "/by_following" => "articles#by_following", as: "articles_by_following"
    patch "/:id" => "articles#update"
  end
  
  resources :articles, param: :slug, except: [:update] do
    resources :comments do
      post "/likes" => "comments#like_comment"
    end
    post "/likes" => "articles#like_article"
  end
  resources :categories

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  has_many :likes, class_name: 'CommentReaction', foreign_key: 'comment_id', dependent: :destroy
  belongs_to :commenter, class_name: "User", foreign_key: 'user_id'
  validates_presence_of :body, on: %i[create update], message: "can't be blank"
  validates_length_of :body, within: 2..5000, message: "must be within 5000 characters"
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  rescue_from ActiveRecord::RecordInvalid do |e|
    @error = e.message
    respond_to do |format|
      format.js { render partial: 'layouts/show_errors' }
    end
  end
  
  before_action proc { @comment = Comment.find(params[:id]) }, only: %i(destroy edit update)
  before_action proc { require_same_user @comment }, only: %i(destroy edit)
  def create
    @article = Article.find(params[:article_slug])
    @article.comments.create!(comment_params.merge(commenter: current_user))
    respond_to do |format|
      format.js { render partial: 'layouts/reload' }
    end
  end

  def like_comment
    comment = Comment.find(params[:comment_id])
    like(comment)
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.js { render partial: 'layouts/reload' }
    end
  end

  def update
    @article = Article.find(params[:article_slug])
    @comment.update!(comment_params)
    respond_to do |format|
      format.js { render partial: 'layouts/reload' }
    end
  end 

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_card.html.erb
<div class="comment-card">
  <div class="commenter-img left-sec mr-md-2 mr-1">
   <%= link_to profile_link(comment.user_id) do%>
    <%= image_tag comment.user.image_url.to_s %>
    <% end %>
  </div>
  <div class="pt-0 right-sec">
    <div class='row justify-content-between ml-0 mr-0'>
      <div>
      <%= link_to profile_link(comment.user_id) do%>
        <b class="text-dark"><%= comment.user.username %></b>
      <% end %>
        <span>
          <small class="text-secondary">
            <%= "#{time_ago_in_words(comment.created_at)} ago" %>
          </small>
        </span>
      </div>
      <div class="comment-actions">
      <% if logged_in? && current_user.id == comment.user_id %>
       <%= link_to '<i class="far fa-edit mr-2" title="edit"></i>'.html_safe , 'javascript:void(0)', remote: true %>
        <%= link_to '<i class="fa fa-trash" aria-hidden="true" title="delete"></i>'.html_safe, article_comment_path(@article.slug, comment.id), method: 'delete', data: {confirm: "Are you sure you want to delete this comment?"}, remote: true %>
        <% end %>
      </div>
    </div>
    <div class="comment-body mt-2">
     <div class="comment-cont py-0 my-0">
     <%= sanitize comment.body %>
     </div>
     <%= render 'comments/form', id: "comment_edit_input-#{comment.id}", comment: comment, action: 'Save' %>
      </div>
    <div class="reactions-section comment-reactions-sec">
      <% if logged_in? %>
        <%= link_to(article_comment_likes_path(@article.slug, comment.id), method: 'post', remote: true) do %>
          <i class= '<%= "#{comment.liked_by(current_user) ? 'fas' : 'far'}" %> fa-heart' id="like-button" style="cursor: pointer" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <small><span class="like-count"><%= comment.likes.length %> </span> likes</small>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@article, comment], remote: true do |f| %>
  <div class="form-group mb-4">
    <%= f.text_field :body, placeholder: 'What do you think ?', class: 'quill_container', required: true, id: id %>
    <small class="text-danger error"> </small>
  </div>
  <div class="form-group">
    <%= f.submit action, class: 'btn btn-dark btn-sm' %> <%= content_tag(:button, 'Cancel', class: 'btn btn-light btn-sm cancel-btn') if action == 'Save' %>
  </div>
<% end %>

app/views/comments/_section.html.erb
<div class="comments-sec mt-5">
  <%= logged_in? ? render('comments/form', id: 'comment_create_input', action: 'Leave Comment', comment: @article.comments.build) : render('layouts/banner') %>
  <% unless @article.comments.count.zero? %>
    <h6 class="mt-5"> comments (<%= @article.comments.count %>) </h6>
    <div class="comments">
      <% @article.comments.each do |comment| %>
        <% if  comment.id %>
          <%= render 'comments/card', comment: comment %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>