config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'profile', to: 'users#profile'
  post 'signup', to: 'users#signup_user'
  post 'login', to: 'users#login_user'
  patch 'profile/edit_profile', to: 'users#edit_profile'
  patch 'profile/update_profile_img', to: 'users#update_profile_img'
  get 'users/:id', to: 'users#show'
  post 'users/:id/following', to: 'users#follow_user'
  delete 'logout', to: 'users#logout_user'

  scope "articles" do
    get "/autocomplete" => "articles#autocomplete" 
    get "/search" => "articles#search"
    get "/by_following" => "articles#by_following", as: "articles_by_following"
    patch "/:id" => "articles#update"
  end
  
  resources :articles, param: :slug, except: [:update] do
    resources :comments do
      post "/likes" => "comments#like_comment"
    end
    post "/likes" => "articles#like_article"
  end
  resources :categories

end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  belongs_to :user
  has_many :article_stats, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :article_body, presence: true, length: { minimum: 10, maximum: 20_000 }
  after_create :generate_unique_slug
  searchkick suggest: [:title]
  scope :search_import, -> { includes(:user) }

  private

  def search_data
    { title: title, number_of_reads: number_of_reads, article_body: article_body, username: user.username }
  end

  def generate_unique_slug
    slug = "#{title.parameterize}-#{id}"
    update(slug: slug)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i(edit update)
  before_action :set_article_by_id, only: [:update]
  before_action :require_user, only: %i(new update edit like_article)
  before_action proc { require_same_user(@article) }, only: %i(edit update destory)

  def new
    @article = Article.new
  end

  def autocomplete
    search = Article.search params[:query], { 
      suggest: [:full_text], 
      fields: ["title^10", "article_body"],
      limit: 10
    }

    
    # binding.pry
    
  
    render json: search.map(&:title)
  end

  def show
    @article = Article.includes(likes: :user, comments: :user).find_by(slug: params[:slug])
    unless @article.user == current_user
      @article.increment!(:number_of_reads)
      ArticleStat.create!(user_id: current_user ? current_user.id : request.remote_ip, article: @article)
    end
  rescue => e
    nil
  end

  def by_following; end

  def edit; end

  def destroy
    @article = Article.destroy(params[:slug])
    flash[:info] = "Article was successfully deleted"
    redirect_to profile_path
  end

  def search
    @search_results = Article.search params[:query], suggest: [:full_text], fields: ["title^10", "article_body", {"username^10" => :exact}]
  end
 
  def create
    article_data = calculate_time_to_read(article_params)
    @article = Article.new(article_data)
    @article.user = current_user
    if @article.save
      flash.now[:success] = "Article was successfully created"
      redirect_to article_path @article.slug
    else
      render "new"
    end
  end

  def update
    article_data = calculate_time_to_read(article_params)
    if @article.update(article_data)
      flash.now[:success] = "Article was successfully updated"
      redirect_to article_path @article.slug
    else
      render "edit"
    end
  end

  def index
    @articles = Article.all
  end

  def like_article
    article = Article.find_by(slug: params[:article_slug])
    like(article)
  end

  private

  def set_article
    @article = Article.find_by(slug: params[:slug])
  end

  def set_article_by_id
    @article = Article.find(params[:id])
  end

  def calculate_time_to_read(params)
    article_words = params[:article_body].split(" ").length
    params[:time_to_read] = "#{(article_words.to_f / 200).ceil} min"
    params
  end

  def article_params
    params.require(:article).permit(:title, :article_body, :image_url, category_ids: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def url
    url_for(only_path: true)
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true, :html => {class: "form-container", role: "form", multipart: true})  do |form| %>
  <div class="form-group mb-4">
    <%= form.text_field :title, placeholder: 'title', required: true %>
    <small class="text-danger"><%= "Title #{@article.errors[:title][0]}" if @article.errors[:title].any? %> </small>
  </div>
  <div class="form-group mb-4" >
    <label for='upload-cover-img'><i class="fa fa-upload" aria-hidden="true"></i> <span>Upload Image (optional)</span></label> <i class="fa fa-times fa-2x" id="close-icon" aria-hidden="true" style="display: <%= 'inline' unless @article.image_url.blank? %>"></i>
    <%= form.file_field :image_url, 'up-data': '.image-preview'.to_json, accept: "image/*", id: 'upload-cover-img' %>
  </div>
  <div class="img-preview m-3 px-4" style="background: url(<%= @article.image_url.to_s %>) no-repeat center center; background-size: contain; display: <%= 'block' unless @article.image_url.blank? %>">
  </div>
  <div class="form-group mb-4" >
    <%= form.text_area :article_body, class: 'quill_container', placeholder: 'Write your story....',  required: true %>
    <small class="text-danger"><%= "Article body #{@article.errors[:article_body][0]}" if @article.errors[:article_body].any? %> </small>
  </div>
  <div class="form-group mb-4" >
    <%= form.collection_select :category_ids, Category.all, :id, :name, {}, {multiple: "multiple", id: "selectpicker"} %>
  </div>
  <div class="form-group">
    <%= form.submit class: 'btn btn-dark btn-lg' %>
  </div>
<% end %>

app/views/articles/by_following.erb
<h4 class="mt-5">Articles By people you follow</h4>
<div class="featured-articles my-4">
    <% current_user.articles_by_following.each do |article| %>
      <%= render 'layouts/article_card', article: article, truncValue: {article_body: 120, article_title: 40} %>
    <% end %>
  </div>

app/views/articles/edit.html.erb
<div class="create-article-page my-5">
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<h2><%= link_to 'Create new article', new_article_path %></h2>
<table>
<thead>
<tr><th>Title</th> <th>article_body</th> <th>Time Written</th></tr>
</thead>
<tbody>
<% @articles.each do |article| %>
  <tr>
  <td><%= article.title %></td>
  <td><%= article.article_body.truncate(50) %></td>
  <td><%= article.created_at %></td>
  <td><%= link_to 'Show', article_path(article) %></td>
  <td><%= link_to 'Edit', edit_article_path(article) %></td>
  <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"} %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/articles/new.html.erb
<div class="create-article-page my-5">
  <%= render 'form' %>
</div>

app/views/articles/search.html.erb
<h4 class= "mt-5"> Search results for "<%= params[:query] %>" </h4>
<div class="featured-articles my-4">
  <%= if @search_results.blank? then "<h3>Couldn't find articles matching your search </h3>".html_safe end %>
    <% @search_results.each do |article| %>
      <%= render 'layouts/article_card', article: article, truncValue: {article_body: 120, article_title: 40} %>
    <% end %>
  </div>

app/views/articles/show.html.erb
<div class="article-page">
  <div class="article-title mb-4 text-center title"> 
    <h1><%= @article.title %></h1>
     </div>
     <%= link_to "/users/#{@article.user_id}" do %>
  <div class="extra-details justify-content-center align-items-center">
    <div class="profile-img pr-1"> <%= gravatar_for @article.user, '-md' %> </div>
    <div class='extra-info text-secondary'>
      <div class="pr-2 pl-1 mb-1" >
      <span class="text-success">@<%= @article.user.username %></span>
      <% if logged_in? %>
      <%= link_to check_following(@article.user, 'Following', 'Follow'),
       "/users/#{@article.user_id}/following",
        method: :post,
         class: "btn btn-sm border-dark text-dark ml-2 #{check_following(@article.user, 'following')} follow-btn",
         remote: true, onclick: "return false" %>
      <% end %>
      </div>
      <div>
        <span class="pl-1 pr-1"><%= Date.strptime(@article.created_at.to_s).to_formatted_s(:short) %></span>. 
        <span> <%= "#{@article.time_to_read} read" %></span>
      </div>
    </div>
  </div>
  <% end %>
  <% unless @article.image_url.to_s.empty? %>
    <div class="article-image-container" style="background: url(<%= @article.image_url.to_s %>) no-repeat center center; background-size: cover;">.</div>
  <% end %>
  <div class="article-body-container mt-5">
    <div class="article-body mb-5"><%= sanitize @article.article_body %> </div>
    <div class="reactions-section article-reactions-sec">
      <% if logged_in? %>
        <%= link_to(article_likes_path(@article.slug), method: 'post', remote: true) do %>
          <i class= '<%= "#{@article.liked_by(current_user) ? 'fas' : 'far'}" %> fa-heart' id="like-button" style="font-size: 22px; cursor: pointer" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <span class="badge badge-dark mr-2 ml-1"><span class="like-count"><%= @article.likes.length %> </span> likes</span>
      <span id="comments-count" class="badge badge-dark"> <%= pluralize(@article.comments.count, 'comment') %> </span>
    </div>
    <div>
    <%= render 'comments/section' %>
    </div>
  </div>
</div>