config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'profile', to: 'users#profile'
  post 'signup', to: 'users#signup_user'
  post 'login', to: 'users#login_user'
  patch 'profile/edit_profile', to: 'users#edit_profile'
  patch 'profile/update_profile_img', to: 'users#update_profile_img'
  get 'users/:id', to: 'users#show'
  post 'users/:id/following', to: 'users#follow_user'
  delete 'logout', to: 'users#logout_user'

  scope "articles" do
    get "/autocomplete" => "articles#autocomplete" 
    get "/search" => "articles#search"
    get "/by_following" => "articles#by_following", as: "articles_by_following"
    patch "/:id" => "articles#update"
  end
  
  resources :articles, param: :slug, except: [:update] do
    resources :comments do
      post "/likes" => "comments#like_comment"
    end
    post "/likes" => "articles#like_article"
  end
  resources :categories

end

app/views/pages/about.html.erb
<h1>About alpha blog</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<%# <%= link_to 'All articles', articles_path %>
<%# <%= link_to "About", about_path %>
<% if @articles.any? %>
  <div class="articles-section">
    <div class="selected-articles-sec row my-4">
      <div class="left-scrolling-sec pr-xl-5" >
        <span class="intersect-elem"> </span>
        <div class="top-article mb-5">
          <h2 class="d-none d-md-block mb-3 font-weight-bold">Top Article</h2> <div class="d-md-none h4 mb-2 font-weight-bold">Top Article</div>
          <%= link_to article_path(@top_article.slug) do %>
            <div class='article-card-image-container mb-3' ><%= image_tag(@top_article.image_url.present? ? @top_article.image_url.to_s : 'Blog.jpg', class: "article-img") %></div>
            <div class='article-card-title mb-1 text-dark'> <%= @top_article.title.truncate(60) %> </div>
          <% end %>
          <div class="row mt-2 ml-0">
            <%= link_to profile_link(@top_article.user_id) do%>
              <div class="profile-img pr-1"> <%= gravatar_for @top_article.user, '-sm' %> </div>
              <div class='extra-info text-secondary'>
                <div class="pr-2 pl-1" ><span class="text-success">@<%= @top_article.user.username %></span></div>
                <div>
                <% end %>
                <span class="pl-1 pr-1"><%= Date.strptime(@top_article.created_at.to_s).to_formatted_s(:short) %></span>. 
                <span> <%= "#{@top_article.time_to_read} read" %></span>
              </div>
            </div>
          </div>
          <%= link_to article_path(@top_article.slug) do %>
            <div class='article-card-body mt-1'><%= sanitize @top_article.article_body.gsub(/(<.+?>)|(<.+?\/>)/, '').truncate(600) %> </div>
          <% end %>
        </div>
        <% if logged_in? && @recommended.present? %>
          <div class="recommended-articles mb-5">
            <h5 class="font-weight-bold">Recommended (Based on your reading history)</h5>
            <hr class="mb-3">
              <%= render partial: 'layouts/horizontal_card', collection: @recommended, as: :article %>
          </div>
        <% end %>
        <% if logged_in?  && @articles_by_people_you_follow %>
          <h5 class="font-weight-bold"><%= link_to 'By people you follow', articles_by_following_path  %> </h5>
          <hr>
          <div class="personalised-articles mb-4">
            <% @articles_by_people_you_follow.each do |article| %>
              <%= render 'layouts/article_card', article: article, truncValue: {article_body: 220, article_title: 50} %>
            <% end %>
          </div>
        <% end %>
        <% if !logged_in? %>
          <%= render 'layouts/banner' %>
        <% end %>
        <h5 class= 'font-weight-bold <%= 'mt-5' unless @articles_by_people_you_follow || @recommended.present? %>' >Featured Articles</h5>
        <hr>
        <div class="featured-articles my-4">
            <%= render partial: 'layouts/article_card', as: :article, collection: @featured_articles.sample(9), locals: { truncValue: {article_body: 100, article_title: 40} } %>
        </div>
      </div>
      <div class="popular-articles pt-3 pb-5 pl-5 mr-0 pr-0">
        <h5 class="mb-3 font-weight-bold">Popular articles</h5>
        <hr>
        <% @popular_articles.take(7).each do |article| %>
          <%= link_to article_path(article.slug) do %>
            <div class="mb-3">
              <h6><%= article.title%></h6>
              <small><span class="text-success">@<%= article.user.username %></span></small>
            </div>
          <% end %>
        <% end %>
        <hr>
      </div>
    </div>
  </div>
<% end %>