config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'profile', to: 'users#profile'
  post 'signup', to: 'users#signup_user'
  post 'login', to: 'users#login_user'
  patch 'profile/edit_profile', to: 'users#edit_profile'
  patch 'profile/update_profile_img', to: 'users#update_profile_img'
  get 'users/:id', to: 'users#show'
  post 'users/:id/following', to: 'users#follow_user'
  delete 'logout', to: 'users#logout_user'

  scope "articles" do
    get "/autocomplete" => "articles#autocomplete" 
    get "/search" => "articles#search"
    get "/by_following" => "articles#by_following", as: "articles_by_following"
    patch "/:id" => "articles#update"
  end
  
  resources :articles, param: :slug, except: [:update] do
    resources :comments do
      post "/likes" => "comments#like_comment"
    end
    post "/likes" => "articles#like_article"
  end
  resources :categories

end

app/views/layouts/_article_card.html.erb
<div class='article-card'>
  <%= link_to article_path(article.slug) do %>
    <div class='article-card-image-container mb-3' ><%= image_tag(image_url(article), class: "article-img") %></div>
    <div class='article-card-title mb-1 text-dark'> <%= article.title.truncate(truncValue[:article_title]) %> </div>
    <div class='article-card-body mt-1'><%= sanitize article.article_body.gsub(/(<.+?>)|(<.+?\/>)/, '').truncate(truncValue[:article_body]) %> </div>
  <% end %>
  <div class="extra-details mt-2">
    <%= link_to profile_link(article.user_id) do%>
      <div class="profile-img pr-1"> <%= gravatar_for article.user, '-sm' %> </div>
      <div class='extra-info text-secondary'>
        <div class="pr-2 pl-1" ><span class="text-success">@<%= article.user.username %></span></div>
        <div>
        <% end %>
        <span class="pl-1 pr-1"><%= Date.strptime(article.created_at.to_s).to_formatted_s(:short) %></span>. 
        <span> <%= "#{article.time_to_read} read" %></span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_banner.html.erb
<div class="site-banner row mb-5">
  <div class="banner col-5">
    <div class="typing-img">
      <%= image_tag 'pngguru.com-id-bbckh.png' %>
    </div>
  </div>
  <div class="col-5 sign-up-notice">
    <h3 class="notice-text mb-4">Why wait longer? Join in the conversations now!</h3>
    <div class="sign-up-button">
      <button class="signup-modal-trigger">Get started</button>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
  $('#toast-container').hide()
    <% flash.each do |f| %>
    <% type = f[0].to_s %>
    toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-container">
    <div class="row align-items-center" >
      <div class="col">
        <ul>
          <li> Contact us</li>
          <li>+2348140064376</li>
          <li>ezenwaogbonna1@gmail.com</li>
          <li>ezenwa.andela.@gmail.com</li>
        </ul>
      </div>
      <div class="col- text-right">
        <span>Copyright &copy; 2019</span>
      </div>
    </div>
  </div>
</footer>
 

app/views/layouts/_header.html.erb
<div class="nav-header-cont">
<nav class="header">
  <div class="nav-container" >
    <div class="row justify-content-between align-items-center">
    <div class="hamburger col-2 d-md-none"> <a href="javascript:void(0)"><i class="fas fa-bars"></i></a> </div>
      <div class="col-6 col-md-5 text-center text-md-left">
        <%= link_to '<span class="site-title">Ozone\'s blog</span>'.html_safe, root_path %>
      </div>
      <div class="col-5 d-none d-md-block">
        <div class="search-container">
          <%= form_tag("/articles/search", method: :get) do %>
            <%= text_field_tag :query, params[:query], class: "search-input-field", placeholder: "Search..", type: "search" %>
            <button type="submit"><i class="fa fa-search"></i></button>
          <% end %>
        </div>
      </div>
      <div class="nav-item dropdown col-2">
        <% if logged_in? %>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= gravatar_for current_user, '-sm' %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <div class="text-center text-success"><%= "Hi #{current_user.username}" %></div>
            <%= link_to 'My Profile', profile_path, class: "dropdown-item" %>
            <%= link_to 'Create Article', new_article_path, class: "dropdown-item" %>
            <%= link_to 'Log out', logout_path, method: :delete, class: "dropdown-item" %>
          </div>
        <% else %>
          <a href="javascript:void(0)" class="login-modal-trigger dropdown-toggle font-weight-bold"> Log In </a>
        <% end %>
      </div>
    </div>
  </nav>
  <%= render('layouts/navbar') unless url.match(/profile|users/) %>
  </div>

app/views/layouts/_horizontal_card.html.erb
<div class="user-article-cards">
  <div class="article-img" >
    <%= link_to article_path(article.slug) do %>
      <%= image_tag image_url(article) %>
    </div>
  <% end %>
  <div class="article-content">
    <%= link_to article_path(article.slug) do %>
      <div class="user-article-title">
        <h5 class="text-dark d-sm-none"><%= article.title.truncate(40) %></h5>
        <h5 class="text-dark d-none d-sm-block"><%= article.title.truncate(80) %></h5>
      </div>
      <div class="user-article-body d-none d-md-block">
        <%= sanitize article.article_body.gsub(/(<.+?>)|(<.+?\/>)/, '').truncate(200) %>
      </div>
    <% end %>
    <div class="row text-secondary mt-1 mt-md-3">
      <div class="additional-details col-md-5">
      <small>
          By <span class="text-success"><%= "@#{article.user.username}"%></span>
          In <span class="text-faded"><%= article.categories[0].name %> </span>
        </small>
      </div>
      <div class="col-md-7 text-md-right" >
      <small>
        <span class="pl-1 pr-1"><%= Date.strptime(article.created_at.to_s).to_formatted_s(:short) %></span>. 
        <span> <%= "#{article.time_to_read} read" %></span>
        </small>
        
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default categories-cont nav-hidden">
<div class="d-block d-md-none text-center">
        <div class="search-container">
          <%= form_tag("/articles/search", method: :get, class: "search-form") do %>
            <%= text_field_tag :query, params[:query], class: "search-input-field", placeholder: "Search..", type: "search" %>
            <button type="submit" class="d-none d-md-block"><i class="fa fa-search"></i></button>
          <% end %>
        </div>
      </div>
  <span class="btn-sm scroll-prev-btn"><</span>
      <div class="container-fluid categories-list">
        <div class="nav navbar-nav align-items-md-center">
          <%= link_to "Home", root_path, class: "px-md-3 py-2 #{url == '/' && 'active'}" %>
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category.id), class:"px-md-3 py-2 #{params[:id].to_i == category.id && 'active'}" %>
          <% end %>
        </div>
      </div>
      <span class="btn-sm scroll-next-btn">></span>
    </nav>
    <!-- <%= if logged_in? and current_user.is_admin?; link_to('Create Category', new_category_path, class: "dropdown-item"); end %> -->

app/views/layouts/_reload.js.erb
window.location.reload()

app/views/layouts/_show_errors.js.erb
$('.error').html("<%= @error %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins|Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora|Noto+Sans|PT+Serif&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <div class='modal'>
      <%= render 'users/sign_up_form' %>
      <%= render 'users/login_form' %>
    </div>
    <%= render 'layouts/footer' unless url.match(/profile|users/) %>
    
  </body>
</html>